version: '3.7'

services:
  gateway:
    image: traefik:v2.7
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - ssn-network

  identity-web:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratosweb.entrypoints=web'
      - 'traefik.http.routers.kratosweb.rule=Host(`id.servidorsemnome.com`)'
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: ./apps/identity/Dockerfile
    networks:
      - ssn-network

  warehouse:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - warehouse:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - ssn-network

  warehouse-migrate:
    build:
      context: ./packages/warehouse
    depends_on:
      - warehouse
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - ssn-network

networks:
  ssn-network:
    external: true

volumes:
  kratos-sqlite:
  warehouse: