version: '3.7'

services:
  gateway:
    image: traefik:v2.7
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - ssn-network

  identity-web:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.identity.entrypoints=web'
      - 'traefik.http.routers.identity.rule=Host(`id.servidorsemnome.com`)'
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: ./apps/identity/Dockerfile
    environment:
      PUBLIC_BASE_DOMAIN: ${PUBLIC_BASE_DOMAIN}
      PUBLIC_DASHBOARD_URL: ${PUBLIC_DASHBOARD_URL}
      PUBLIC_REGISTER_ENABLED: ${PUBLIC_REGISTER_ENABLED}
      PUBLIC_REGISTER_INVITE_ONLY: ${PUBLIC_REGISTER_INVITE_ONLY}
      PUBLIC_REGISTER_INVITES_PER_USER: ${PUBLIC_REGISTER_INVITES_PER_USER}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - ssn-network

  warehouse:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - warehouse:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - ssn-network

  warehouse-migrate:
    build:
      context: ./packages/warehouse
    depends_on:
      - warehouse
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - ssn-network

  gatekeeper-web:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gatekeeper.entrypoints=web'
      - 'traefik.http.routers.gatekeeper.rule=Host(`gk.servidorsemnome.com`)'
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: ./apps/gatekeeper/Dockerfile
    environment:
      PUBLIC_IDENTITY_URL: ${PUBLIC_IDENTITY_URL}
    networks:
      - ssn-network

  gatekeeper-redis:
    image: redis:7.0.5-alpine
    command: redis-server --requirepass ${GK_REDIS_PASSWORD} --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - gatekeeper:/data/redis

networks:
  ssn-network:
    external: true

volumes:
  warehouse:
  gatekeeper: